source 'https://rubygems.org'
ruby '2.2.1'
gem 'roda'
gem 'sequel'
gem 'sqlite3'
gem 'rack-unreloader', require: 'rack/unreloader'
gem 'racksh'
gem 'puma'
gem 'foreman'
gem 'activesupport'
gem 'sequel_id_pagination', github: 'mitchellhenke/sequel_id_pagination'
